### ISSUE TITLE
3rd level children not showing up in dump()

### ISSUE THREAD

**Issue by jeremyabrahams** [studioespresso/craft3-navigate#1]
I've created a simple nav. 
3 levels deep only using a custom URL for testing simplicity.
![screen shot 2018-07-02 at 11 00 34 am](https://user-images.githubusercontent.com/1126912/42171413-3aa87026-7de7-11e8-8c62-0e7843d13470.png)

I wasn't getting my 3rd level link "Level-3" (above) to display. I tried a couple different versions of macros I had up my sleeve along with the snippet you provide in the README. 
`node.children|length` always was showing as 0.

I ran a simple dump on the array
`{% set navigation = craft.navigate.raw('mynav') %}`
<pre>{{ dump(navigation) }}</pre>

And as I suspected children of "Level-2" was returning NULL

`array(1) {
  [0]=>  object(studioespresso\navigate\models\NodeModel)#1087 (20) {
    ["id"] => int(17)
    ["name"] => string(7) "Level-1"
    ["navId"] => int(2)
    ["siteId"] => int(1)
    ["type"] => string(3) "url"
    ["url"] => string(16) "http://cnn.com/1"
    ["order"] => int(0)
    ["parent"] => int(0)
    ["classes"] => NULL
    ["enabled"] => int(1)
    ["elementId"] => NULL
    ["elementType"] => NULL
    ["children"] => array(1) {
      [0] => object(studioespresso\navigate\models\NodeModel)#1091 (20) {
        ["id"] => int(18)
        ["name"] => string(7) "Level-2"
        ["navId"] => int(2)
        ["siteId"] => int(1)
        ["type"] => string(3) "url"
        ["url"] => string(16) "http://cnn.com/2"
        ["order"] => int(0)
        ["parent"] => int(17)
        ["classes"] => NULL
        ["enabled"] => int(1)
        ["elementId"] => NULL
        ["elementType"] => NULL
        ["children"] => NULL
        ["blank"] => int(0)
        ["_errors":"yii\base\Model":private] => NULL
        ["_validators":"yii\base\Model":private] => object(ArrayObject)#1094 (1) {
          ["storage":"ArrayObject":private] => array(2) {
            [0] => object(yii\validators\RequiredValidator)#1096 (15) {
              ["skipOnEmpty"] => bool(false)
              ["requiredValue"] => NULL
              ["strict"] => bool(false)
              ["message"] => string(28) "{attribute} cannot be blank."
              ["attributes"] => array(4) {
                [0] => string(4) "type"
                [1] => string(5) "navId"
                [2] => string(6) "siteId"
                [3] => string(4) "name"
              }
              ["on"] => array(0) {
              }
              ["except"] => array(0) {
              }
              ["skipOnError"] => bool(true)
              ["enableClientValidation"] => bool(true)
              ["isEmpty"] => NULL
              ["when"] => NULL
              ["whenClient"] => NULL
              ["_events":"yii\base\Component":private] => array(0) {
              }
              ["_eventWildcards":"yii\base\Component":private] => array(0) {
              }
              ["_behaviors":"yii\base\Component":private] => NULL
            }
            [1] => object(yii\validators\SafeValidator)#1095 (13) {
              ["attributes"] => array(14) {
                [0] => string(2) "id"
                [1] => string(4) "name"
                [2] => string(5) "navId"
                [3] => string(7) "enabled"
                [4] => string(9) "elementId"
                [5] => string(11) "elementType"
                [6] => string(4) "type"
                [7] => string(3) "url"
                [8] => string(6) "siteId"
                [9] => string(5) "order"
                [10] => string(6) "parent"
                [11] => string(5) "blank"
                [12] => string(7) "classes"
                [13] => string(8) "children"
              }
              ["message"] => NULL
              ["on"] => array(0) {
              }
              ["except"] => array(0) {
              }
              ["skipOnError"] => bool(true)
              ["skipOnEmpty"] => bool(true)
              ["enableClientValidation"] => bool(true)
              ["isEmpty"] => NULL
              ["when"] => NULL
              ["whenClient"] => NULL
              ["_events":"yii\base\Component":private] => array(0) {
              }
              ["_eventWildcards":"yii\base\Component":private] => array(0) {
              }
              ["_behaviors":"yii\base\Component":private] => NULL
            }
          }
        }
        ["_scenario":"yii\base\Model":private] => string(7) "default"
        ["_events":"yii\base\Component":private] => array(0) {
        }
        ["_eventWildcards":"yii\base\Component":private] => array(0) {
        }
        ["_behaviors":"yii\base\Component":private] => array(0) {
        }
      }
    }
    ["blank"] => int(0)
    ["_errors":"yii\base\Model":private] => NULL
    ["_validators":"yii\base\Model":private] => object(ArrayObject)#1088 (1) {
      ["storage":"ArrayObject":private] => array(2) {
        [0] => object(yii\validators\RequiredValidator)#1089 (15) {
          ["skipOnEmpty"] => bool(false)
          ["requiredValue"] => NULL
          ["strict"] => bool(false)
          ["message"] => string(28) "{attribute} cannot be blank."
          ["attributes"] => array(4) {
            [0] => string(4) "type"
            [1] => string(5) "navId"
            [2] => string(6) "siteId"
            [3] => string(4) "name"
          }
          ["on"] => array(0) {
          }
          ["except"] => array(0) {
          }
          ["skipOnError"] => bool(true)
          ["enableClientValidation"] => bool(true)
          ["isEmpty"] => NULL
          ["when"] => NULL
          ["whenClient"] => NULL
          ["_events":"yii\base\Component":private] => array(0) {
          }
          ["_eventWildcards":"yii\base\Component":private] => array(0) {
          }
          ["_behaviors":"yii\base\Component":private] => NULL
        }
        [1] => object(yii\validators\SafeValidator)#1093 (13) {
          ["attributes"] => array(14) {
            [0] => string(2) "id"
            [1] => string(4) "name"
            [2] => string(5) "navId"
            [3] => string(7) "enabled"
            [4] => string(9) "elementId"
            [5] => string(11) "elementType"
            [6] => string(4) "type"
            [7] => string(3) "url"
            [8] => string(6) "siteId"
            [9] => string(5) "order"
            [10] => string(6) "parent"
            [11] => string(5) "blank"
            [12] => string(7) "classes"
            [13] => string(8) "children"
          }
          ["message"] => NULL
          ["on"] => array(0) {
          }
          ["except"] => array(0) {
          }
          ["skipOnError"] => bool(true)
          ["skipOnEmpty"] => bool(true)
          ["enableClientValidation"] => bool(true)
          ["isEmpty"] => NULL
          ["when"] => NULL
          ["whenClient"] => NULL
          ["_events":"yii\base\Component":private] => array(0) {
          }
          ["_eventWildcards":"yii\base\Component":private] => array(0) {
          }
          ["_behaviors":"yii\base\Component":private] => NULL
        }
      }
    }
    ["_scenario":"yii\base\Model":private] => string(7) "default"
    ["_events":"yii\base\Component":private] => array(0) {
    }
    ["_eventWildcards":"yii\base\Component":private] => array(0) {
    }
    ["_behaviors":"yii\base\Component":private] => array(0) {
    }
  }
}`

![screen shot 2018-07-02 at 11 08 10 am](https://user-images.githubusercontent.com/1126912/42171882-76547be6-7de8-11e8-96cb-52a9cff010e1.png)

**Comment by janhenckens** [comment]
Thanks for that, I'll have a look right away :)

(Note that the plugin hasn't been released yet so there might be some things that aren't working. Hoping to have it in the store by the end of the week)

**Comment by janhenckens** [comment]
Hey Jeremy,
This should work now. Can you update and give it a go? Thanks!

**Comment by jeremyabrahams** [comment]
Works perfect, thank you!
