### ISSUE TITLE
active when url is a child url

### ISSUE THREAD

**Issue by chrisrowe** [studioespresso/craft3-navigate#10]
I'd love to have top level nav items show as active if I'm on a url which is clearly a child, even if the child isn't defined in the plugin.

e.g. `<a href="/foo" class="active">Foo</a>` when the full url is `/foo/bar`.

**Comment by janhenckens** [comment]
Hey Chris, that should be possible :)
Are you using one of the render functions or printing the navigation yourself?

**Comment by chrisrowe** [comment]
@janhenckens At the moment I'm doing the navigation myself, but either would be fine. Just getting access to `node.slug` would help a lot.

**Comment by janhenckens** [comment]
Gotcha! Pushed the changes to fix this, will release an update by the end of the week.

Thanks for suggesting this!
