### ISSUE TITLE
Error when an entry referenced in navigation no longer exists

### ISSUE THREAD

**Issue by camilleb** [studioespresso/craft3-navigate#11]
Error is

> Call to a member function getUrl() on null

in `src/services/NodesService.php` line 84.

Obviously, the error disappear when we removed the old entry in the navigation, but maybe add a test on `$element` could prevent this error.

**Comment by janhenckens** [comment]
Thanks for reporting that! 
Fixed in 92ab1742e98ef7f772410e14e2a3ca39c76b8d79. Update will be out by tomorrow evening.

**Comment by janhenckens** [comment]
Released 1.1.1 with this fix just now.
Thanks for using my plugin! Feel free to make an issue for any other issues or suggestions you have :)
