### ISSUE TITLE
Setting unknown property: studioespresso\navigate\models\NavigationModel::defaultNodeType

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-navigate#12]
I get this error when I try to access a navigation item. 

`throw new UnknownPropertyException('Setting unknown property: ' . get_class($this) . '::' . $name);` on line 209.

**Comment by jan-dh** [comment]
![image](https://user-images.githubusercontent.com/5801781/43135039-567605b6-8f44-11e8-8959-258c3dbf9a41.png)

When I try to click on one of these items.

**Comment by janhenckens** [comment]
Hey Jan
Are you on the last version of the plugin (1.1.0)? 
And could you try running `./craft migrate/up --plugin=navigate` to run the migration included in the last update? Should run on install/update but maybe something went wrong.

**Comment by janhenckens** [comment]
That's very strange, running this (`./craft migrate/up --plugin=navigate`) works on my test site so if your site have the plugin installed that should work...

**Comment by janhenckens** [comment]
Could you copy/paste me the line for the plugin in your composer.json? Should give me a clearer view on what you have installed.

**Comment by jan-dh** [comment]
composer.json:
```
 "require": {
    "craftcms/cms": "3.0.16.1",
    "vlucas/phpdotenv": "^2.4.0",
    "nystudio107/craft-seomatic": "3.1.4",
    "studioespresso/craft-navigate":"^1.1",
```
Like this?

**Comment by janhenckens** [comment]
Yep, but that all looks good. Could you try reinstalled the plugin to see if the problem persists? (make a backup of the database cause the navigation & nodes will be removed on uninstall)

**Comment by janhenckens** [comment]
Hey Jan
Could you try the following? 
Remove the migration for `m180720_174411_removeDefaultTypeField` from the `migrations` table in your project and run `./craft migrate/up --plugin=navigate` again?

Had the same issue on a project here where it said the migration had run but the column was still in the table.

**Comment by nicolasbinet** [comment]
I had the same issue with version 1.1.1
Re-running the "./craft migrate/up --plugin=navigate" command solved the problem for me.

**Comment by janhenckens** [comment]
Thanks for letting me know Nicolas! Looks like the migration isn't always being run on update. 
Investigating further! 🕵🏻‍♂️

**Comment by jan-dh** [comment]
Fixed the issue of the plugin commands not being available in the CLI and got it to work with the `./craft migrate/up --plugin=navigate`.

**Comment by janhenckens** [comment]
This one is *finally* fixed now. Had to remove the field from the initial migration as well.
