### ISSUE TITLE
Editing nav containing deleted element throws error

### ISSUE THREAD

**Issue by i-just** [studioespresso/craft3-navigate#13]
When trying to edit a nav which contains deleted element, I get the following error: 

```
Impossible to invoke a method ("getCpEditUrl") on a null variable.
in vendor/studioespresso/craft-navigate/src/templates/_edit.twig at line 58 
```

I'm using Navigate v1.1.1. Can you please have a look into it?

**Comment by janhenckens** [comment]
Thanks for catching this! 
I’m on holiday at the moment, will be back on Sunday. Fix should be out soon after!

**Comment by i-just** [comment]
Hi Jan,

Hope you had great holiday. Thanks for pushing a fix. Could you also apply
it to when a category is missing (lines 67-69)?

Thanks,
Iwona

**Comment by janhenckens** [comment]
Ha yes, will do! That's the downside of quick fixes when the brain is still in holiday mode :)
Coming right up!

**Comment by janhenckens** [comment]
Fixed in 1.1.3. Should be in the store soonish, there are some issues with updates coming through there so hang on for a bit.

**Comment by janhenckens** [comment]
It's in the store!

Thanks again for reporting this and for using my plugin :)

**Comment by i-just** [comment]
Great, thanks!
