### ISSUE TITLE
2 nodes active because same word in title

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft3-navigate#14]
<img width="1026" alt="screen shot 2018-09-07 at 13 33 10" src="https://user-images.githubusercontent.com/42932673/45217000-d3a43400-b2a2-11e8-9145-1282e3a5a456.png">

Because 'research' is in the title it sets the node 'research' on active while it is not a parent.

**Comment by janhenckens** [comment]
Related to #10
