### ISSUE TITLE
Home node

### ISSUE THREAD

**Issue by NickToye** [studioespresso/craft3-navigate#17]
My home navigation doesn't register an active state because unlike 'about', 'contact' etc...  it doesn't have a matching node in the url.  Unless I put the url as 'home' which I don't want to do.

Please advise.

**Comment by janhenckens** [comment]
Hey Nick

Can you share how you're printing the navigation in your template? Thanks!

**Comment by NickToye** [comment]
Hi Jan,

code snippet below:

`{% set nav = craft.navigate.raw('mainNavigation') %}
    {% import _self as macros %}
    {% macro renderNode(node) %}
        {% import _self as macros %}
        <li class="o-list-inline__item  u-padding-horizontal {% if node.classes|length %}{{ node.classes }}{% endif %}">
            <a href="{{ node.url }}" class="{% if node.active %}active{% endif %}"
            {% if node.blank %}target="_blank" rel="noopener"{% endif %}>{{ node.name }}
            </a>
            {% if node.children|length %}
                <ul>
                {% for child in node.children %}
                    {{ macros.renderNode(child) }}
                {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endmacro %}

    <nav class="c-nav">
        <ul class="o-list-inline u-margin-none">
        {% for node in nav %}
            {{ macros.renderNode(node) }}
        {% endfor %}
        <li class="o-list-inline__item  u-margin-horizontal  u-padding-horizontal c-btn c-btn--primary c-btn--rounded c-btn--small">
          <a href="#" class="" data-izimodal-open="#modal-custom">Quote Me</a>
        </li>
        </ul>
    </nav>`

**Comment by janhenckens** [comment]
That seems correct, and when I try to reproduce this on my end it works for the homepage node.
Let me see if you understand your navigation: "home" is in the nav, but it links to the homepage, so to `/` of the site?

Could you maybe also post the HTML that the snippet above is rendering?

**Comment by NickToye** [comment]
```
<nav class="c-nav">
        <ul class="o-list-inline u-margin-none">
                                    <li class="o-list-inline__item  u-padding-horizontal ">
            <a href="//localhost:3000/" class="">Home
            </a>
                    </li>
    
                                    <li class="o-list-inline__item  u-padding-horizontal ">
            <a href="//localhost:3000/about" class="">About
            </a>
                    </li>
    
                                    <li class="o-list-inline__item  u-padding-horizontal ">
            <a href="//localhost:3000/work" class="">Work
            </a>
                    </li>
    
                                    <li class="o-list-inline__item  u-padding-horizontal ">
            <a href="//localhost:3000/products" class="active">Products
            </a>
                    </li>
    
                                    <li class="o-list-inline__item  u-padding-horizontal ">
            <a href="//localhost:3000/blog" class="">Blog
            </a>
                    </li>
    
                                    <li class="o-list-inline__item  u-padding-horizontal ">
            <a href="//localhost:3000/contact" class="">Contact
            </a>
                    </li>
    
                <li class="o-list-inline__item  u-margin-horizontal  u-padding-horizontal c-btn c-btn--primary c-btn--rounded c-btn--small">
          <a href="#" class="" data-izimodal-open="#modal-custom">Quote Me</a>
        </li>
        </ul>
    </nav>
```

**Comment by NickToye** [comment]
Is it because I am on localhost?

**Comment by janhenckens** [comment]
Can you try if the active state works on an actual url? (pixels.local in your case)

**Comment by NickToye** [comment]
Jan, yeah sorry it does work, I think I mentioned in the previous comment.  You can probably close this issue as its not really an issue, unless you feel you want it to work on localhost?

**Comment by janhenckens** [comment]
No worries, just making sure.
Yeah, the craft functions I'm using to check the url probably don't play well with localhost:3000. I'll close this for now
