### ISSUE TITLE
[Request] Make name in CP clickable to entry

### ISSUE THREAD

**Issue by jeremyabrahams** [studioespresso/craft3-navigate#2]
![4556d5f437e54d78ca13ab51e28651ce _screen shot 2018-07-02 at 1 54 30 pm](https://user-images.githubusercontent.com/1126912/42178810-b7d20e28-7dff-11e8-93f1-0bd9709941fe.png)

It would be a really nice feature for my content admins to be able to use this as a pseudo site map. If they could click on the node's name and be taken to that entry (or open the custom URL popup) right from the `admin/navigate/edit` screen

**Comment by janhenckens** [comment]
Opening the entry in a new tab is something that should be easy enough, and show the edit popover for custom urls too.

Adding it to the list for 1.1, focusing on actually shipping it first :)

**Comment by richhayler** [comment]
This would also help understand which entry a links actually refers to in the CP. Once you have created the link you have no way to tell in the control panel which entry the link actually points to or the option to change that without having to delete the link and recreate it.

**Comment by janhenckens** [comment]
Added in 1.1.0!
