### ISSUE TITLE
FR: Titles

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-navigate#29]
Would be nice to have the option to add titles in between menu's. Atm we sometimes have big footer menu's with some subtitles. Subtitles go into translatables now and it's a bit of a hassle to template.

**Comment by janhenckens** [comment]
Hey @jan-dh, sounds like a good idea. 
We usually make 3/4 separate navigations to solve the header/menu problem, but this would be neat too. Then you could add titles on level 0, loop those and get the children on level 1. Does that sound like what you're after?

**Comment by jan-dh** [comment]
We go for separate navigations for each menu item, what I'm refering to is for example a footer like this:

![image](https://user-images.githubusercontent.com/5801781/61786654-752a6a80-ae0e-11e9-8c52-ddcadec1d674.png)

Each footer item has a title above it, that you can't really fit into the navigation now. Would be nice to have a navigation item type "title", so you can just loop over the nodes and check something like

```
{% if node.type == "title" %}
  <h3>{{node.name}}</h3>
{% endif %}
```

**Comment by janhenckens** [comment]
Sounds good!

**Comment by janhenckens** [comment]
Hey @jan-dh, just released an update with a first attempt at this. Can you give it a try? Feel free to comment or reopen this issue with any feedback!

**Comment by jan-dh** [comment]
Really nice!
