### ISSUE TITLE
FR: enable nav for site

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft3-navigate#30]
Feature request:
We have a multi site and we can edit each navigation for each site now.
But the footer navigation should not be enabled for the primary website because it is not used there. Would this be possible in the future?

**Comment by janhenckens** [comment]
Could try not adding any items to the footer navigation for the primary site? 

That way the conditional `{% if craft.navigate.raw('navHandle')|length %}` should return false and thus not render anything

**Comment by carolineboeykens** [comment]
It is more the idea that their wouldn't be confusion for the content managers in the control panel. Because they would see this footer navigation but it isn't for site A but for site B.

**Comment by janhenckens** [comment]
Just released this, could you give it a try @carolineboeykens? Happy to look at any feedback/issues you might have 🙂
