### ISSUE TITLE
craft.navigate.raw sometimes returns false

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-navigate#33]
Have a multi-site setup (30+ sites), working on a local database.  In a footer, I have set up 4 different navigation items. Only one of them shows up, the rest returns false. 

The setup from one of the false ones:

![image](https://user-images.githubusercontent.com/5801781/62031267-3b2edf00-b1e7-11e9-98c1-304c00c71902.png)

```
{% set col1 = craft.navigate.raw("footerCol1") %}
<pre>
    {{ dump(col1) }}
</pre>
```

This returns `bool(false)`

Have also tried with single quotes like this:

`{% set col1 = craft.navigate.raw('footerCol1') %}`

Same result.

I'm on the latest version of the plugin and Craft 3.1.34.2.

**Comment by janhenckens** [comment]
First off, could you try cleaning the Navigate cache under Utilities > Clear caches? Just to be sure that this isn't a caching issue (if it is, we'll try and solve that too 🙂)

**Comment by jan-dh** [comment]
Changing one of the handles fixed it. I guess it was a cache thing 😢. Is there a way to clear caches automatically when adding new handles? Kind of confusing that you still have to do that manually.

**Comment by janhenckens** [comment]
I try to clear caches when just about anything changes in the navigation from the CP (adding something, changing a title, updating the order, removing an item etc all cause a cache clear & warm).

Did you notice the issue after adding a new site? And what is your workflow with the navigations vs the sites?

**Comment by jan-dh** [comment]
I added the navigations to existing sites, so no new sites were added. The navigation is unique for each site and exists on all sites.

**Comment by janhenckens** [comment]
Gotcha, thanks for the extra info! I'll try to get a test setup with 10+ sites up & running this week to see if I can reproduce this.

**Comment by jan-dh** [comment]
Thanks! If I run into this again, I'll try to provide some more info.
