### ISSUE TITLE
FR: show uri for selected entries/categories

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-navigate#34]
It sometimes happens that clients name a page the same thing twice in a website. So without having any info on the uri, it's very much a trial and error to see what entry you are selecting.

**Comment by janhenckens** [comment]
In the entries modal you mean? Or on the navigation page itself?

**Comment by jan-dh** [comment]
In the navigation page itself would be perfect

**Comment by janhenckens** [comment]
Should be easy enough 👍 Coming soon to a plugin store near you 😉

**Comment by jan-dh** [comment]
Awesome!

**Comment by janhenckens** [comment]
Done!

<img width="457" alt="Screenshot 2019-08-29 at 20 45 03" src="https://user-images.githubusercontent.com/755428/63967523-ea3c3000-ca9d-11e9-803d-50322646db4b.png">

Adding another feature and hoping to have both out by Monday!

**Comment by janhenckens** [comment]
Out in 2.4.0!
