### ISSUE TITLE
Feature request, select entries from other sites

### ISSUE THREAD

**Issue by boldenamsterdam** [studioespresso/craft3-navigate#35]
First of all, the current plugin works really nice!
We are using it in a multi-site environment. 

One small improvement we would like to see, is the possibility to select entries from other sites. 
For multi-site environments this can sometimes be really handy.

**Comment by janhenckens** [comment]
Hey there!
Thanks for getting in touch, that sounds like something that should be possible.
I'll have a look at how that would work vs site permissions for the current user, but Craft should have us covered there.

I'll keep you posted!

**Comment by janhenckens** [comment]
Hey @boldenamsterdam, I totally lost track of this issue, sorry about that. Just released an update that includes this.
