### ISSUE TITLE
node.active not working

### ISSUE THREAD

**Issue by thefubon** [studioespresso/craft3-navigate#36]
```{% if node.active %}uk-active{% endif %}```
If I create a normal URl mnu, node.Active is not added to me

**Comment by thefubon** [comment]
<img width="556" alt="Снимок экрана 2019-12-10 в 11 55 45" src="https://user-images.githubusercontent.com/43171309/70514123-07c07180-1b44-11ea-907d-460b71dc46dd.png">

**Comment by janhenckens** [comment]
Hey there, could you also add the url which you're on when trying this?

**Comment by thefubon** [comment]
[](https://monopixel.ru/games)

**Comment by thefubon** [comment]
Entry menu  - it works

**Comment by thefubon** [comment]
```
{% import _self as macros %}
          {% macro renderNode(node) %}
              {% import _self as macros %}
            <li class="{% if node.classes|length %}{{ node.classes }}{% endif %} {% if node.active %}uk-active{% endif %}">
                  <a  href="{{ node.url }}" class="{% if node.active %}uk-active{% endif %}"
                {% if node.blank %}target="_blank" rel="noopener"{% endif %}><span>{{ node.name }}</span>
                  </a>
                  {% if node.children|length %}
                      <ul>
                      {% for child in node.children %}
                          {{ macros.renderNode(child) }}
                      {% endfor %}
                      </ul>
                  {% endif %}
              </li>
          {% endmacro %}

          <div class="uk-navbar-right">
              {% set nodes = craft.navigate.raw('navHandle') %}
              <ul class="uk-navbar-nav uk-navbar-parent-icon">
              {% for node in nodes %}
                  {{ macros.renderNode(node) }}
              {% endfor %}
              </ul>
          </div>
```

**Comment by janhenckens** [comment]
Is the item in the navigation a link to an entry or to a manually added url?

**Comment by thefubon** [comment]
URL
<img width="850" alt="Снимок экрана 2019-12-10 в 12 11 34" src="https://user-images.githubusercontent.com/43171309/70515364-45be9500-1b46-11ea-8379-4fbcef01f82a.png">

**Comment by janhenckens** [comment]
Ok, I'll investigate & get back to you asap!

**Comment by thefubon** [comment]
thanks

**Comment by janhenckens** [comment]
Hey @thefubon, I just released an update to fix this. Can you update & try again? Thanks!

**Comment by thefubon** [comment]
Thanks, Now everything works. Only there is one problem as in other navigation plugins. Work only in the default language. If I change the language of the site, the active menu class is not displayed.

**Comment by janhenckens** [comment]
Is the link & menu item the same for the other language? If you could post the same info as above for the second language that would help a lot to reproduce & debug :)

**Comment by thefubon** [comment]
Maybe I'm doing something wrong. But my menu is different. If I make the same links. Switching to the EN version will not work for me
![menu](https://user-images.githubusercontent.com/43171309/70694187-13d93a00-1cd0-11ea-818b-28f2de6f12ce.png)

**Comment by janhenckens** [comment]
Could you also add the HTML you see on the English menu?

**Comment by thefubon** [comment]
Standard code from the documentation
```
{% import _self as macros %}
  {% macro renderNode(node) %}
      {% import _self as macros %}
    <li class="{% if node.classes|length %}{{ node.classes }}{% endif %} {% if node.active %}uk-active{% endif %}">
  <a  href="{{ node.url }}" class=""{% if node.blank %}target="_blank" rel="noopener"{% endif %}><span>{{ node.name }}</span></a>
          {% if node.children|length %}
              <ul class="uk-list">
              {% for child in node.children %}
                  {{ macros.renderNode(child) }}
              {% endfor %}
              </ul>
          {% endif %}
      </li>
  {% endmacro %}

  <nav class="uk-navbar-container uk-navbar-transparent uk-background-default">
    <div class="uk-container uk-container-medium" data-uk-navbar>
      <div class="uk-navbar-left">
        <ul class="uk-navbar-nav">
        {% set nodes = craft.navigate.raw('navHandle') %}
        {% for node in nodes %}
            {{ macros.renderNode(node) }}
        {% endfor %}
        </ul>
      </div>
    </div>
  </nav>
```

**Comment by thefubon** [comment]
What is missing is a variable that would add a link to the language inside the menu
```href="{{ node.url }}"```

**Comment by thefubon** [comment]
site.com/menu-link (site.com**/en/**menu-link)

**Comment by janhenckens** [comment]
I was referring to the html of the English page when you inspect it. Thanks!

**Comment by thefubon** [comment]
Please tell me where to look?

**Comment by janhenckens** [comment]
Like the comment you posted earlier(https://github.com/studioespresso/craft3-navigate/issues/36#issuecomment-563932550). On the frontend of the English page, use the inspect function in your browser and there I need the navigation item that should be active.

**Comment by thefubon** [comment]
https://github.com/thefubon/craftcms/tree/master/craft/templates

**Comment by thefubon** [comment]
https://github.com/thefubon/craftcms/blob/master/craft/templates/_layout.twig

191 lines

**Comment by janhenckens** [comment]
@thefubon That is the twig template. In my comment I mentions the actual html in your browser, could you supply that? That way I can check the url you have in the CP versus the url that is in the navigation on the page itself.

**Comment by thefubon** [comment]
<img width="519" alt="Снимок экрана 2019-12-12 в 13 21 38" src="https://user-images.githubusercontent.com/43171309/70708669-219cb880-1cec-11ea-9e3b-8ba238508835.png">

**Comment by thefubon** [comment]
<img width="521" alt="Снимок экрана 2019-12-12 в 13 21 52" src="https://user-images.githubusercontent.com/43171309/70708684-282b3000-1cec-11ea-9c12-d0861e687035.png">

**Comment by thefubon** [comment]
<img width="1369" alt="Снимок экрана 2019-12-12 в 13 22 08" src="https://user-images.githubusercontent.com/43171309/70708700-2eb9a780-1cec-11ea-8280-f1e075bd9ed0.png">
