### ISSUE TITLE
FR: don't return node if it's not type heading and has no url

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-navigate#39]
At this point, we're having a customer removing entries from the CMS without adjusting the navigation. Templating breaks since, the navigation still shows the entry, but without uri. Is it possible to not return entries if the type is `entry` and it has no valid url?

**Comment by janhenckens** [comment]
Hey Jan! Valid point.

Here's how I'd like to solve it: 
- when an entry is removed, we also remove the navigation item
- when an entry is disabled, we disabled the navigation item

I have a couple of other fixes in the pipeline for a release, I'll try to add this so it's out soon!

**Comment by jan-dh** [comment]
Sound good!

**Comment by janhenckens** [comment]
Out in 2.8.
