### ISSUE TITLE
Error: Impossible to access an attribute ("id") on a null variable in "navigate/_includes/_node".

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-navigate#42]
Since the last update I get this error when I try to access one of the menu's:

```Error: Impossible to access an attribute ("id") on a null variable in "navigate/_includes/_node".```

![image](https://user-images.githubusercontent.com/5801781/76213309-b428f700-620a-11ea-97a8-b044849d6595.png)

**Comment by janhenckens** [comment]
Hey @jan-dh, not sure where that's happening. Could you post the full stack dump? Thanks!

**Comment by janhenckens** [comment]
Hey @jan-dh, just released an update that fixes this, sorry about the trouble!

**Comment by jan-dh** [comment]
Thanks!
