### ISSUE TITLE
FR: make caching optional

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-navigate#43]
While the caching is really nice, in some scenario's you want to avoid it. Would be nice if you could add a param to set it to false.

**Comment by janhenckens** [comment]
Right now the plugin will only cache when devMode is **not** enabled. Adding a way to overwrite that would be nice to have. I'll have a look!

**Comment by jan-dh** [comment]
Would love to see this option implemented, if possible on a menu level. This plugin doesn't play nice with Blitz cache, since updating a menu, doesn't trigger blitz to purge caches.

**Comment by janhenckens** [comment]
Hey @jan-dh. The plugin has a hook for Blitz but that'll probably only work with Blitz 2, not with the latest.
I have some time this weekend, will try to add it first thing!

**Comment by janhenckens** [comment]
Fixed in 2.7.0! See the docs [here](https://github.com/studioespresso/craft3-navigate#disabling-caching).

**Comment by jan-dh** [comment]
Sweet! Thanks for the quick reply!
