### ISSUE TITLE
Same nav on multiple sites

### ISSUE THREAD

**Issue by nflorentin** [studioespresso/craft3-navigate#47]
Hi,

I don't find how to have automatically the same nav on multiple sites. I'm developing a project available in 2 languages so I have 2 sites. My navigation will be the same on both sites, so I wonder if it is possible to have the second site using the exact same nav as the first one without having to make two times the same configuration.

I think that the plugin does not have this feature. Perhaps there is some hacky way to do that ?

Thanks for your work!

**Comment by janhenckens** [comment]
Hey! You're right, that's not possible right. 
Off the top of my head, here's how I'd like to solve it: make `craft.navigate.getRaw()` take a second option parameter where you can pass the site it. If you don't pass anything there, we'll use the current site. 
In your case you could do  `craft.navigate.getRaw('handle', craft.app.sites.getPrimarySite().id)` and that should do the trick.

Does that sound good? :)

**Comment by nflorentin** [comment]
Janhenckens, that's a perfect solution and not hacky at all :).
Thanks you very much!

**Comment by janhenckens** [comment]
@nflorentin included in today's update, can you give it a try? Thanks!
