### ISSUE TITLE
ErrorException when accessing a Navigation item

### ISSUE THREAD

**Issue by robinbraibant** [studioespresso/craft3-navigate#52]
When I enter the Navigate plugin in the Craft backend, and try to enter an item. I get the following error:
`yii\base\ErrorException: Trying to access array offset on value of type bool in /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/studioespresso/craft-navigate/src/extensions/NavigateExtension.php:45
Stack trace:
#0 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError()
#1 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/studioespresso/craft-navigate/src/extensions/NavigateExtension.php(45): craft\web\ErrorHandler->handleError()
#2 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/storage/runtime/compiled_templates/8e/8e39f0bfec5695ba4ec3971beeda32631fde256c99d0581e39c3902d830bd1af.php(113): studioespresso\navigate\extensions\NavigateExtension->parseUrl()
#3 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Extension/CoreExtension.php(1109): __TwigTemplate_68788abb5af52ef1eb96765e6b2d4cfc94bb65aeed9faad8906b9c5e9349b76e->macro_renderNode()
#4 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/storage/runtime/compiled_templates/50/504bb152030b6d05872e4abbd63d260975ffa672cb1674556c476562180ace5f.php(146): twig_call_macro()
#5 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(182): __TwigTemplate_c5ee7eda01d25ded312f65d113a5a23cf45e73194207b88ce04264f493fc46d0->block_content()
#6 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/storage/runtime/compiled_templates/ba/bacae85aae9e0e5360c119be63f9640b798d653b7570f2aeaa965411f61f629d.php(444): Twig\Template->displayBlock()
#7 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(182): __TwigTemplate_8f83693a0d70dfeccf96fc55d3c87e16081025bdd33e09aefd641144ed66c263->block_main()
#8 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/storage/runtime/compiled_templates/ba/bacae85aae9e0e5360c119be63f9640b798d653b7570f2aeaa965411f61f629d.php(309): Twig\Template->displayBlock()
#9 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(182): __TwigTemplate_8f83693a0d70dfeccf96fc55d3c87e16081025bdd33e09aefd641144ed66c263->block_body()
#10 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/storage/runtime/compiled_templates/a8/a8413c7ad09a37c607af9fa9ce1362f60e5e92a8fc66930f09e679c9896169b0.php(85): Twig\Template->displayBlock()
#11 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(405): __TwigTemplate_82555c0e273e57248328a9b8bf3702f3b0f4174bd994e5da379757dbc766ef1b->doDisplay()
#12 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#13 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/storage/runtime/compiled_templates/c0/c0cf1b5b2b258d6056debb870e91841447aa9dc62b83ff6743b3cc72bba1407e.php(56): Twig\Template->display()
#14 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(405): __TwigTemplate_93c21c439df1e40586b0043d17711d116f975ea0d6635d006e42616dc3aa0cf8->doDisplay()
#15 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#16 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/storage/runtime/compiled_templates/ba/bacae85aae9e0e5360c119be63f9640b798d653b7570f2aeaa965411f61f629d.php(154): Twig\Template->display()
#17 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(405): __TwigTemplate_8f83693a0d70dfeccf96fc55d3c87e16081025bdd33e09aefd641144ed66c263->doDisplay()
#18 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#19 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/storage/runtime/compiled_templates/50/504bb152030b6d05872e4abbd63d260975ffa672cb1674556c476562180ace5f.php(61): Twig\Template->display()
#20 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c5ee7eda01d25ded312f65d113a5a23cf45e73194207b88ce04264f493fc46d0->doDisplay()
#21 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#22 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#23 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#24 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#25 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/craftcms/cms/src/web/View.php(392): Twig\Environment->render()
#26 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/craftcms/cms/src/web/View.php(453): craft\web\View->renderTemplate()
#27 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/craftcms/cms/src/web/Controller.php(251): craft\web\View->renderPageTemplate()
#28 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/studioespresso/craft-navigate/src/controllers/DefaultController.php(122): craft\web\Controller->renderTemplate()
#29 [internal function]: studioespresso\navigate\controllers\DefaultController->actionEdit()
#30 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#31 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#32 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction()
#33 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#34 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#35 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#36 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest()
#37 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#38 /data/sites/web/shiclalivestatikbe/subsites/shicla.live.statik.be/public/index.php(23): yii\base\Application->run()
#39 {main}`

**Comment by janhenckens** [comment]
Fixed in 2.7.3, which is out now!
