### ISSUE TITLE
Question: write content migrations

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-navigate#55]
Was wondering if you 'd have an example laying around for content migration for a navigation.

**Comment by janhenckens** [comment]
Hey Jan, 

Have a look at this migration that is included for upgrades from Craft 2 sites with AmNav:

Here we create a navigation: https://github.com/studioespresso/craft3-navigate/blob/master/src/migrations/upgrades/amNav.php#L27, and here we add the nodes https://github.com/studioespresso/craft3-navigate/blob/master/src/migrations/upgrades/amNav.php#L63

Happy to write out a more specific example if you have a little more information.

**Comment by jan-dh** [comment]
This is perfect

**Comment by janhenckens** [comment]
Cheers! Feel free to chat me if you think I can help out :)
