### ISSUE TITLE
Cannot re-order top level nodes with several levels of children

### ISSUE THREAD

**Issue by J-Protz** [studioespresso/craft3-navigate#56]
Craft Version:Craft Pro 3.4.6
Navigate Version: 2.7.0 (Was previously on 1.2, updated to try and solve issue)
PHP Version: 7.4.12
MYSQL: 5.7.31

Navigate.php:

```php
<?php

return [
    "disableCaching" => true,
    "anyoneCanAdd" => false,
    "pluginLabel" => "Navigate",
];

```

I have a navigation menu like this:
<img width="1068" alt="Screen Shot 2021-03-26 at 10 01 35 AM" src="https://user-images.githubusercontent.com/70289763/112643002-430ab080-8e1a-11eb-915d-82f6856eb2ba.png">

And if I try to take the `fabrics` node, and move it to the top, it will say `order updated` yet if i refresh, it goes back.

I have confirmed that there are no errors being thrown, and lower level nodes re-order just fine (the children can be rearranged without issue)

Please help :)!

**Comment by janhenckens** [comment]
Hey Joe, can you check if there is a JS error on the page when you drag the node?

**Comment by J-Protz** [comment]
<img width="791" alt="Screen Shot 2021-03-26 at 11 02 01 AM" src="https://user-images.githubusercontent.com/70289763/112651368-b44e6180-8e22-11eb-9c06-a44b616dcb56.png">
Nothing, and I get this 200 OK network request.

**Comment by janhenckens** [comment]
Strange, I'll try to reproduce and get back to you!

**Comment by J-Protz** [comment]
Thank you!

**Comment by janhenckens** [comment]
Hey @J-Protz, I was able to reproduce this but only when moving the second node to the top and only when both of the them have children. Can you confirm that this is what you're trying to do?

**Comment by J-Protz** [comment]
I'm having issues re-ordering the very top level nodes. It will say `order updated` but upon refresh, no change. @janhenckens

**Comment by J-Protz** [comment]
@janhenckens testing on local this seems to have done it! Will let you know if anything changes once pushed to staging/live. Thank you!

**Comment by J-Protz** [comment]
@janhenckens  just want to update you - all is working :)

**Comment by janhenckens** [comment]
Thanks for the update @J-Protz :)
