### ISSUE TITLE
FR: Specify list of available classes that can be selected on a node

### ISSUE THREAD

**Issue by janhenckens** [studioespresso/craft3-navigate#57]

**Comment by dave-agilepixel** [comment]
A quick fix I've popped in for the moment is along the lines of 

```
{{ forms.selectField({
    label: "Classes"|t('navigate'),
    id: 'classes',
    name: 'classes',
    options: [
        { value: 'is-blue', label: "Blue"|t('navigate') },
        { value: 'is-orange', label: "Orange"|t('navigate') },
        { value: 'is-green', label: "Green"|t('navigate') },
        { value: 'is-black', label: "Black"|t('navigate') },
        { value: 'is-none', label: "None"|t('navigate') }
    ],
    value: node.classes,
    toggle: true,
}) }}
```

in the _editor.twig file

I'm not sure how to get that into an external config file, but it works exactly as required

**Comment by janhenckens** [comment]
Hey @dave-agilepixel, this is included in today's release. You can find the docs on it [here](https://github.com/studioespresso/craft3-navigate/tree/develop#css-class-option-list).

Can you give it a try? Feel free to get back to me if you run into any issues!

**Comment by dave-agilepixel** [comment]
@janhenckens That works perfectly, super easy to setup and use, thanks so much!

**Comment by janhenckens** [comment]
Cheers!
