### ISSUE TITLE
Styling in Craft 3.7.38

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft3-navigate#63]
Something went wrong here. Could you check it out?

![Screenshot 2022-04-25 at 15 04 14](https://user-images.githubusercontent.com/42932673/165094918-379874ab-4c5a-49d0-b26d-6fa2d4311388.png)

Craft: 3.7.38
Navigate: 2.9.0

**Comment by janhenckens** [comment]
Hmm, That's strange :) Thanks for reporting, I'll have a look!
