### ISSUE TITLE
Runtime error after installing in Craft 4

### ISSUE THREAD

**Issue by robinbraibant** [studioespresso/craft3-navigate#64]
After installing the plugin in Craft 4.0.2. you get following error when you click the Navigate menu item in the control panel.

<img width="673" alt="Screenshot 2022-05-16 at 20 21 21" src="https://user-images.githubusercontent.com/32429797/168658116-e9ca4968-5a08-44aa-afa2-e6d783d9c8fd.png">

You are using `craft.config.allowAdminChanges`, but craft.config has been deprecated. The current implementation can be `craft.app.config.general.allowAdminChanges`.
Current installed version of the plugin: 3.0.0

**Comment by janhenckens** [comment]
Thanks for reporting this @robinbraibant, fixed in 3.0.1.
