### ISSUE TITLE
FR: Navigation per site or site group.

### ISSUE THREAD

**Issue by belkin** [studioespresso/craft3-navigate#68]
Can we have site or site group setting where we can decide to enable or disable specific navigation like the structures? 

![image](https://user-images.githubusercontent.com/3419659/211261289-3a4caf26-36e1-4af3-808c-74506fe87e40.png)

**Comment by belkin** [comment]
Oh, there is such an setting. Sorry for the ticket ..

**Comment by janhenckens** [comment]
Hey @belkin, you just beat me to it :) 
Good to see you found the setting, let me know if you run into anything else or if you have other ideas for improvements.
