### ISSUE TITLE
Can't create new navigations on environments with allowAdminChanges = false

### ISSUE THREAD

**Issue by twitcher07** [studioespresso/craft3-navigate#70]
I updated the plugin from version 3.0.2 to version 3.1.2 and now I'm unable to create new navigations on environments that have allowAdminChanges disabled even though "Navigations can be created on read-only environments" is enabled.

Here's a screenshot of the navigations with allowAdminChanges enabled:
![image](https://github.com/studioespresso/craft3-navigate/assets/8517321/ace3827c-5785-4e5c-8022-d0e41bfa6a8f)

Here is the same site in a production environment:
![image](https://github.com/studioespresso/craft3-navigate/assets/8517321/2b03f1b9-a0a6-469c-9883-0494965db77c)

Here's my plugin settings:
![image](https://github.com/studioespresso/craft3-navigate/assets/8517321/3a41079a-7587-4783-b361-e12f041954f6)

Version of Craft i'm using is 4.4.13. Downgrading back to version 3.0.2 seems to be my only solution for now.

**Comment by janhenckens** [comment]
Hey @twitcher07, sorry about that, must have missed it when I updated the navigation overview UI. This has now been fixed in 3.1.3!

**Comment by twitcher07** [comment]
@janhenckens ok I can confirm that I can now create navigations on production environments. Thanks for fixing that!
