### ISSUE TITLE
An extra slash in the URL generates an error. 

### ISSUE THREAD

**Issue by KarelJanVanHaute** [studioespresso/craft3-navigate#75]
When switching between multiple sites within a navigation, an extra slash is added to the 'site' parameter. This results in an error.

![image](https://github.com/studioespresso/craft-navigate/assets/88485726/7ccce12a-a8e2-4448-ae1b-d8b129755e71)

The error is due to the fact that I want to use that parameter to get the site in other code. But the extra slash should not be there.

**Comment by janhenckens** [comment]
Hey @KarelJanVanHaute, this should already be fixed in the latest version (I see you're in 3.1.3, is fixed in 3.2.1)
